name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ '**' ]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: crystallang/crystal
    steps:
    - uses: actions/checkout@v2
    - name: Install libudis86
      run: |
        apt-get update -y && \
        apt-get install -y software-properties-common && \
        add-apt-repository ppa:sbasalaev/pub && \
        apt-get update -y && \
        apt-get install -y udis86
    - name: Install dependencies
      run: shards install
    - name: Run tests
      run: crystal spec
